### PR TITLE
Multitenancy

### PR DESCRIPTION
**Pull request by adamki**

### CODE REVIEW

**Comment by adamki** [comment]
This is ready to go and in need of review. The new gem (shouldamatchers) is great for AR validations and checking... but if you dont want to use it, then it should not causer any issues.

**Comment by mbburch** [comment]
Cool, I'm a fan of shoulda. Thanks for adding it. I'll take a look at this.

**Comment by mbburch** [comment]
Test looks good, and so does the rest. I read it pretty closely. Have  a couple questions, regarding login and dashboard. It looks like upon login there are 3 different dashboard paths for different user roles again, but in routes I only see the "/dashboard" going to seller show. Where are others directed? I'm good to push... just wondering.

**Comment by adamki** [comment]
Hi! So, the i didn't modify the previous '/dashboard' routes. This includes the 'root/dashboard' and the 'admin/dashboard'.  As of now the third one, mine, simple goes to 'seller/dashboard'.  This space is protected and can not be viewed by other users and sellers.

**Comment by mbburch** [comment]
Cool. I'll go ahead and merge it then.

**Pull request merged**
